sudo: required
services:
  - docker

language: node_js
node_js:
  - v10.15.2

before_install:
  - docker build -t profemzy/docker-react -f Dockerfile.dev .

script:
  - docker run profemzy/docker-react npm run build
  - docker run profemzy/docker-react npm test